config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post '/' => 'posts#create'
  resources :posts do
    resources :comments
  end

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :users, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_secure_password
	has_many :comments, dependent: :destroy
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with:  VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	
	def admin?
		self.role == 'admin'
	end

	def editor?
		self.role == 'editor'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  before_action :search_met
  
  helper_method :current_user, :posts_list

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def posts_list
  	@posts = Post.all
  end


  def search_met
    @q = Post.ransack(params[:q])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
	    @comment = @post.comments.create(comment_params)
	    respond_to do |format|
			format.html { redirect_to post_url(@post) }
			format.js
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy if current_user.id == @comment.user_id
		respond_to do |format|
			format.html { redirect_to post_url(@post) }
			format.js
		end
	end

	private

	def comment_params
		if current_user
			hash = params.require(:comment).permit(:text)
			hash[:user_id] = current_user.id
			return hash
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	
	def index
		@q = Post.ransack(params[:q])
 		@posts = @q.result.page(params[:page])
		# @posts = @search.result.paginate(page: params[:page])
		#@posts = @search.result
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@new_comment = Comment.new(post: @post)
		respond_to do |format|
			format.html
			format.json { render :json => @comments.to_json(include: :user) }
			format.js
		end
	end

	# .select(:id, :text, :user_id)
	# 	@new = @comments.each { 
	# 		|c| c[:user_id] = User.find(c[:user_id]).email 
	# 	}

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		respond_to do |format|
			format.html { redirect_to posts_url }
			format.js
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_url
	end

	private 

		def post_params
			params.require(:post).permit(:content, :title)
		end

	# def comments_to_json_hash(comments)
	# 	@array = Array.new
	# 	comments.each do |c|
	# 		@hash = Hash.new
	# 		@hash[:id] = c.id
	# 		@hash[:text] = c.text
	# 		@hash[:email] = User.find(c[:user_id]).email
	# 		@array << @hash
	# 	end
	# 	return @array
	# end

	# def search_params
	# 	params.require(:search).permit(:text)
	# end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by_email(params[:user][:email])
		if user && user.authenticate(params[:user][:password])
			session[:user_id] = user.id
			redirect_to root_url
		else
			flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      		render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def about
		
	end

	def contact
		
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def search?
		params[:q] == nil
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <span>
    <h4>
      <small><%= comment.user.email %> says:</small>
      <small class="pull-right" ><%= comment.created_at %></small>
      <small>
        <% if current_user == comment.user %>
          <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, remote: true %>
        <% end %>
      </small>
    </h4>
  </span>
  <div class="well well-sm"><%= comment.text %></div>
<% end %>

app/views/comments/create.js.erb
$('#all_comments').html("ALL COMMENTS(<%= @post.comments.count %>):");

app/views/comments/destroy.js.erb
$('#all_comments').html("ALL COMMENTS(<%= @post.comments.count %>):");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog on Rails</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
        <div id="wrapper">
        <header>
          <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <%= link_to "MyMicroBlog", root_path , :class => "navbar-brand" %>
            </div>
            <ul class="nav navbar-nav">
              <li><%= link_to "Blog", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to current_user.email, root_path  %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              <% else %>
                <li><%= link_to "Log in", login_path %></a></li>
                <li><%= link_to "Sign up", signup_path %></a></li>
              <% end %>
            </ul>
          </div>
        </nav>
        </header>
        <div class="col-md-3 col-md-push-9 right_section">
          <%= search_form_for @q do |f| %>
          <div class="input-group">
           <span class="input-group-btn">
              <div class="actions">
                <%= f.submit "Search", class: "btn btn-default" %>
              </div>
            </span>
             <div class="field">
             <%= f.text_field :content_cont, placeholder: "Search by title...", class: "form-control" %>
           </div>
           </div>
          <% end %>

          <!-- <div class="input-group">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
              <input type="text" class="form-control">
            </div> -->
          <div class="panel panel-default all_posts" id="extended_desktop"> 
              <div class="panel-heading"><h3 class="panel-title">ALL POSTS</h3></div>
              <div class="panel-body collapsed_list">
                <ul>
                  <% posts_list.each do |post|%>
                    <li><%= link_to post.title , post %></li>
                  <% end %>
                </ul>
              </div>
          </div>
          <div id="collapse_mobile">
            <div id="non_collapsed" class="panel panel-default all_posts"> 
                <div class="panel-heading"><h3 class="panel-title">ALL POSTS</h3></div>
                <button id="ggwp" class="btn btn-default" type="button" data-toggle="collapse" data-target="#demo">Extend all posts</button>
              <div id="demo" class="collapse">
                  <div class="panel-body collapsed_list">
                    <ul>
                      <% posts_list.each do |post|%>
                        <li><%= link_to post.title , post %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-9 col-md-pull-3 main_section nopadding">
           <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/posts/_post.html.erb
<%= div_for post, class: "panel panel-default" do %>
  	<div class="panel-heading">
  		<h3 class="panel-title"><%= post.title %></h3>
  	</div>
	<div class="panel-body">
		<p><%= post.content %></p>
		<span class="time_created"><%= post.created_at %></span>
		<%= link_to "Read more...", post , :class => "pull-right" %>
  	</div>
<% end %>

app/views/posts/create.js.erb
$('div#posts').prepend("<%= escape_javascript(render @post) %>");
$(".panel-body ul").append('<li><%= link_to @post.title , @post %></li>');

app/views/posts/index.html.erb
<% if !search? %>
  <h2>Search results:</h2>
<% end %>

<div id="posts">
	<%= render @posts %>
</div>

<%= will_paginate @posts %>

<% if current_user && current_user.admin? && search? %>
  <%= form_for :post , remote: true do |f| %>
  	<fieldset>
  	<div class="control-group">
        <div class="controls">
          <%= f.text_field :title , placeholder: "Post title..." %>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= f.text_area :content, :id => "comment_area", placeholder: "Post content..." %>
        </div>
      </div>

      <div class="control-group">
        <!-- Button -->
        <div class="controls">
          <%= f.submit "Create", class: "btn btn-success pull-right" %>
        </div>
      </div>
      <br><br><br>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"><%= @post.title %></h3></div>
    <div class="panel-body">
      <p><%= @post.content %></p>
      <span class="time_created">
        <%= @post.created_at %>
      </span>
      <% if current_user && current_user.admin? %>
        <%= link_to "DELETE", @post, method: :delete, :id => "delete-btn", :class => "pull-right", data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
</div>

<% if current_user %>
  <div class="page-header">
    <h5>YOUR COMMENT:</h5>
  </div>

  <%= form_for [@post, @new_comment], remote: true, class: "form-horizontal" do |f| %>
  <fieldset>
    <div class="control-group">
      <div class="controls">
        <%= f.text_area :text , :id => "comment_area" , :placeholder => "Your comment..." %>
      </div>
    </div>

    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <%= f.submit "Comment", :id => "sendComment", :class => "btn btn-success pull-right" %>
      </div>
    </div>
    <br><br><br>
  <% end %>
<% end %>

<div class="page-header">
  <h5 id="all_comments">ALL COMMENTS(<%= @comments.count %>):</h5>
</div>

<div id="comments"></div>

<%= javascript_tag do %>
  initPage(<%= current_user.id if current_user %>);
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  	<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, ab.</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi dolor, earum cum delectus doloremque consectetur autem perspiciatis sunt totam culpa ea at necessitatibus vero et veniam nam aut rem, a suscipit beatae numquam facilis. Iste optio repudiandae corporis reiciendis hic rem commodi eaque consequatur. Cum dolorum officia inventore tempora delectus non, commodi praesentium fugit temporibus autem odio, doloremque iste, placeat quod dolor deserunt. Iusto, expedita deserunt, cum obcaecati facilis totam, quaerat aliquam, dolore quasi explicabo autem cumque nostrum maiores. Amet molestias voluptatem cum. Cupiditate sint veritatis aliquid minus, commodi, possimus distinctio sunt! Dolore repellendus nisi totam et, dolorum quas unde!
    <ul id="marked_list" >
		<li>Lorem ipsum dolor.</li>
		<li>Voluptate, recusandae, quam?</li>
		<li>Possimus, harum, quibusdam!</li>
		<li>Illo, asperiores, harum!</li>
		<li>Itaque, repudiandae, vitae.</li>
		<li>Aperiam, accusantium ipsum.</li>
		<li>Beatae, reiciendis, qui.</li>
		<li>Magni, est, doloribus.</li>
	</ul>	
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, ipsum in. Libero fugiat, autem eum quos perspiciatis neque alias! Reprehenderit!</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="panel panel-default">
  <div class="panel-body">

  	<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, ab.</h2>
  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, natus. Reprehenderit porro non commodi ut. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos voluptates ad, temporibus, eaque perspiciatis rem ipsum ratione? Impedit quidem dolores, hic minus. Voluptatibus mollitia eos nisi, expedita quas, laborum praesentium nihil alias dolor enim tenetur ratione perferendis est ipsa consequuntur reiciendis repudiandae quae optio necessitatibus ipsam! Optio, aut, harum? Eaque molestias rem, aperiam necessitatibus sunt architecto iusto ratione, ex impedit.</p>
    <h4>Phone:</h4>
    <p>543-52626-16-3</p>
    <h4>E-Mail</h4>
    <p>dgka@gmail.com</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">
   <%= form_for @user, :class => "form-horizontal" do |f| %>
	  <fieldset>

	    <div id="legend">
	      <legend class="">Sign up</legend>
	    </div>
			<%= render 'shared/error_messages' %>
		<div class="control-group">
	      <!-- First Name -->
	      <label class="control-label" for="email">First name</label>
	      <div class="controls">
	        <%= f.text_field :first_name , :class => "input-xlarge"  , :placeholder => "First name" %>
	      </div>
	    </div>
		
	    <div class="control-group">
	      <!-- Last Name -->
	      <label class="control-label" for="email">Last name</label>
	      <div class="controls">
	        <%= f.text_field :last_name , :class => "input-xlarge"  , :placeholder => "Last name" %>
	      </div>
	    </div>

	    <div class="control-group">
	      <!-- E-mail -->
	      <label class="control-label" for="email">E-mail</label>
	      <div class="controls">
	        <%= f.email_field :email , :class => "input-xlarge" , :id => "email" , :placeholder => "Email" %>
	      </div>
	    </div>
	 
		<div class="control-group">
	      <!-- Password-->
	      <label class="control-label" for="password">Password</label>
	      <div class="controls">
	         <%= f.password_field :password , :class => "input-xlarge" , :id => "password" , :placeholder => "Password" %>
	      </div>
	    </div>

	    <div class="control-group">
	      <!-- Password Confirmation-->
	      <label class="control-label" for="password">Confirmation</label>
	      <div class="controls">
	         <%= f.password_field :password_confirmation , :class => "input-xlarge" , :id => "password" , :placeholder => "Confirmation" %>
	      </div>
	    </div>
	 	<br>
	    <div class="control-group">
	      <!-- Button -->
	      <div class="controls">
	        <%= f.submit "Sign up", :class => "btn" %>
	      </div>
	    </div>
	  <% end %>
  </div>
</div>